activcar/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('rental.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('jobs_list', views.index, name='jobs_list'),
    path('post_offer', views.post_annonce, name='post_offer'),
]

project/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('jobboard.urls')),
    path('accounts/', include('accounts.urls')),
    url(r'^admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobboard/models.py
from django.db import models

from django.utils import timezone
from django.urls import reverse

from accounts.models import Enterprise
from accounts.models import User

# Create your models here.
class Annonce(models.Model):
    LANGUAGES_FRENCH = 'FR'
    LANGUAGES_ENGLISH = 'EN'

    OFFER_CDI = 'CDI'
    OFFER_CDD = 'CDD'
    OFFER_FREELANCE = 'FRE'
    OFFER_STAGE = 'STA'
    OFFER_ALTERNANCE = 'ALT'
    OFFER_FULLTIME = 'FUL'
    OFFER_HALFTIME = 'HAL'

    FIELD_UI = 'UI'
    FIELD_FRONT_END = 'FE'
    FIELD_BACK_END = 'BA'
    FIELD_APP = 'AP'
    FIELD_INFO_ARCHITECTURE = 'AR'
    FIELD_CONTENT_STRATEGY = 'CS'
    FIELD_MANAGEMENT = 'MA'
    FIELD_SOCIAL_MEDIA = 'SM'
    FIELD_MISCELLARY = 'MI'

    LANGUAGES_CHOICES = (
        (LANGUAGES_FRENCH,'French'),
        (LANGUAGES_ENGLISH, 'English'),
    )

    OFFER_CHOICES = (
        (OFFER_CDI,'CDI'),
        (OFFER_CDD, 'CDD'),
        (OFFER_FREELANCE,'Freelance'),
        (OFFER_STAGE, 'Stage'),
        (OFFER_ALTERNANCE,'Alternance'),
        (OFFER_FULLTIME, 'Temps plein'),
        (OFFER_HALFTIME, 'Temps partiel'),
    )

    JOB_FIELDS_CHOICES = (
        (FIELD_UI, 'UI design'),
        (FIELD_FRONT_END, 'Front-end development'),
        (FIELD_BACK_END, 'Back-end development'),
        (FIELD_APP, 'App Development'),
        (FIELD_INFO_ARCHITECTURE, 'Information Architecture'),
        (FIELD_CONTENT_STRATEGY, 'Content Strategy'),
        (FIELD_MANAGEMENT, 'Management'),
        (FIELD_SOCIAL_MEDIA, 'Social Media Expert'),
        (FIELD_MISCELLARY, 'Miscellary'),
    )

    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, db_index=True, unique=True, null=True)
    enterprise = models.ForeignKey('accounts.Enterprise', on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)
    is_available = models.BooleanField(default=True)
    localization = models.CharField(max_length=100, blank=True, null=True)
    contact_email = models.EmailField(max_length=180, null=True)
    url_redirection = models.URLField(max_length=740, blank=True)
    language = models.CharField(max_length=2, choices=LANGUAGES_CHOICES, default=LANGUAGES_FRENCH)
    job_offer = models.CharField(max_length=3, choices=OFFER_CHOICES, default=OFFER_CDI)
    job_fields = models.CharField(max_length=2, choices=JOB_FIELDS_CHOICES, default=FIELD_UI)

    class Meta:
        ordering = ('published_date',)
        verbose_name = 'Annonce'
        verbose_name_plural = 'Annonces'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Annonce, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('job-details', kwargs={'slug', self.slug})


    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.published_date <= now

    def is_upperclass(self):
        return self.model in (self.OFFER_CDI, self.OFFER_CDD)

    def __str__(self):
        return 'Annonce {}'.format(self.title)

jobboard/forms.py
from django import forms
from jobboard.models import Annonce
from accounts.models import Enterprise


class PostAnnonceForm(forms.ModelForm):
    job_offer = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=Annonce.OFFER_CHOICES)
    job_fields = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=Annonce.JOB_FIELDS_CHOICES)

    class Meta:
        model = Annonce
        fields = (
            'title',
            'contact_email',
            'localization',
            'job_offer',
            'job_fields',
            'language',
            'url_redirection',
        )

jobboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.contenttypes.models import ContentType

from django.conf import settings
from django.utils.translation import ugettext as _
from django.core.mail import EmailMessage

from accounts.models import User
from accounts.models import Student
from accounts.models import Employee
from accounts.models import Enterprise

from jobboard.models import Annonce
from accounts.models import Notification

from jobboard.filters import AnnonceFilter

from jobboard.forms import PostAnnonceForm

# Create your views here.
def index(request):
    latest_annonces = Annonce.objects.all().filter(is_available=True)
    number_of_annonces = len(latest_annonces)
    annonce_filter = AnnonceFilter(request.GET, queryset=latest_annonces)

    return render(request, 'index.html', {
        'filter': annonce_filter,
        'annonce_filter': annonce_filter,
        'number_of_annonces': number_of_annonces,
    })


@login_required(login_url=reverse_lazy('login'), redirect_field_name=None)
def post_annonce(request):
    if request.method == 'POST':
        form = PostAnnonceForm(request.POST, request.FILES)
        if form.is_valid():
            # car = form.save(commit=False)
            #car.owner = request.user
            # car.save()
            instance = form.save(commit=False)
            instance.save()

            receiver = User.objects.filter(email=instance.email).first()
            content_type = ContentType.objects.get(model='annonce')

            notif = Notification.objects.create(
                receiver=receiver,
                content_type=content_type,
                object_id=instance.id,
                status='annonce'
            )

            notif.save()

            messages.add_message(
                request, messages.SUCCESS, _('Annonce ajoutée. N\'oubliez pas de la publier quand elle sera prête.')
            )
            return redirect('jobs_list')
        else:
            print(form.errors)
            messages.add_message(
                request, messages.ERROR, _('Une erreur est survenue.')
            )
    else:
        form = PostAnnonceForm(data=request.GET)

    return render(request, 'post_an_annonce.html', {
        'form': form
    })

jobboard/templates/base.html
{% load staticfiles %}
{% load i18n %}
{% load notification_tags %}
<!DOCTYPE html lang="en">
  <html>
  <head>
    <meta charset="UTF-8">
    <meta name="description" content="Rental cars between individuals.">
    <meta name="author" content="Délita Makanda">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>dopejob - {% block title %}{% endblock %}{% block head_title %}{% endblock %}</title>
    <link href="//fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="{% static 'styles/app.css' %}" rel="stylesheet" />
  </head>

<body>
    <main class="wrapper">
        <div class="header">
            <div class="container">
                <nav>
                    <div class="nav-wrapper">
                        <a class="brand-logo" href="{% url 'index' %}"><img class="cld-hidpi" data-src="{% static 'images/logo.png' %}" style="max-width: 48px" src="{% static 'images/logo.png' %}">
    </a>
                        <ul class="fl-right">
                            <li><a href="{% url 'jobs_list' %}">{% trans 'Liste des annonces' %}</a></li>
                            <li><a href="{% url 'post_offer' %}">{% trans 'Poster une annonce' %}</a></li>
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'profile' %}">{% trans 'Mon espace' %}</a></li>
                            <li><a href="{% url 'logout' %}">{% trans 'Se déconnecter' %}</a></li>
                            {% else %}
                            <li><a href="{% url 'login' %}">{% trans 'Se connecter' %}</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </nav>
                {% block headerContent %}{% endblock %}
            </div>
        </div>
        <div id="{% block bodyId %}genericPage{% endblock %}" class="body">
            <div class="container">
                {% if messages %}
                <ul class="alert-container">
                    {% for message in messages %}
                    <li{% if message.tags %} class="alert-messages alert-{{ message.tags }}"{% endif %}>{{ message }}<span class="close-alert">x</span></li>
                    {% endfor %}
                </ul>
                {% endif %}
                {#% if request.user.is_authenticated %#}
                  <!--<ul class="authenticated-menu">
                    <li>
                        <a href="{ url 'notification' }">
                          {% if request.user %}
                            <i class="globe red active icon"></i>
                          {% else %}
                            <i class="globe icon"></i>
                          {% endif %}
                        </a>
                    </li>
                </ul>-->
                {#% endif %#}
                {% block content %}{% endblock %}
            </div>
        </div>
        <div class="footer">
            <div class="container">
                &copy; 2018 - dopejob
            </div>
        </div>
    </div>

    <script type="text/javascript" src="{% static 'vendors/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendors/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/app.js' %}"></script>

    <script>
    var csrftoken = $.cookie('csrftoken');
    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    $(document).ready(function() {
        {% block domready %}
        {% endblock %}
    });
    </script>
</body>

</html>

jobboard/templates/base2.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html lang="en">
  <html>
  <head>
    <meta charset="UTF-8">
    <meta name="description" content="Rental cars between individuals.">
    <meta name="author" content="Délita Makanda">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>dopejob - {% block title %}{% endblock %}{% block head_title %}{% endblock %}</title>
    <link href="//fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="{% static 'styles/app.css' %}" rel="stylesheet" />
  </head>

<body>
    <main class="wrapper">
        <div id="{% block bodyId %}genericPage{% endblock %}" class="body">
            <div class="container">
                {% if messages %}
                <ul class="alert-container">
                    {% for message in messages %}
                    <li{% if message.tags %} class="alert-messages alert-{{ message.tags }}"{% endif %}>{{ message }}<span class="close-alert">x</span></li>
                    {% endfor %}
                </ul>
                {% endif %}
                {% block content %}{% endblock %}
            </div>
        </div>
        <div class="footer">
            <div class="container">
                &copy; 2018 - dopejob
            </div>
        </div>
    </div>

    <script type="text/javascript" src="{% static 'vendors/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendors/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/app.js' %}"></script>

    <script>
    var csrftoken = $.cookie('csrftoken');
    function csrfSafeMethod(method) {
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });
    $(document).ready(function() {
        {% block domready %}
        {% endblock %}
    });
    </script>
</body>

</html>

jobboard/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load humanize %}
{% load staticfiles %}
{% load pagination_tags %}
{% block title %}{% trans 'Bienvenue' %}{% endblock %}
{% block bodyId %}welcomePage{% endblock %}


{% block content %}
<div class="row">
    <div class="column col3">
        <div class="form-location">
            <form method="get">
                {{ filter.form.as_p }}
                <button type="submit" class="button button-secondary">{% trans 'Rechercher' %}</button>
            </form>
        </div>
    </div>
    <div class="column col6">
        <div class="align-right">
            <a class="button button-primary" href="{% url 'post_offer' %}">{% trans 'Poster une annonce' %}</a>
        </div>
        <ul class="menu-list-cars">
            {% autopaginate filter.qs 8 as filter_search %}
            {% for job in filter_search %}
                <li class="menu-list-cars-item">
                    <a href="#" class="cars">
                        <div class="cars-reference">
                            {% if job.image %}
                            <img src="{{ job.image.url|default_if_none:'#' }}" class="image" alt="{{ job.title }}"/>
                            {% else %}
                            <img src="{% static 'images/none.png' %}" class="image" alt="{{ job.title }}" />
                            {% endif %}
                        </div>
                        <div class="cars-reference cars-description">
                            <div class="car-name">{{ job.title }}</div>
                            <div class="cars-meta">{{ job.get_job_offer_display }}</div>
                        </div>
                        <div class="cars-reference">
                            <div class="cars-location">{{ job.localization }}</div>
                        </div>
                    </a>
                </li>
            {% endfor %}
        </ul>
        {% paginate %}
    </div>
</div>
{% endblock %}

jobboard/templates/notifications.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Notifications' %}{% endblock %}

{% block content %}
{% for notif in notifications %}
  {{ notif }}

  {# for specific is like below #}
  {# `specific_model_name` eg: `comment`, `message`, `post` #}
  {#% if notif._model_name == 'specific_model_name' %#}
    {# do_stuff #}
  {#% endif %#}
{% endfor %}
{% endblock %}

jobboard/templates/post_an_annonce.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans 'Poster une annonce' %}{% endblock %}
{% block bodyId %}postAnnonce{% endblock %}

{% block content %}
<div class="panel">
    <div class="formset">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" name="next" value="{{ next }}" />
            <input type="submit" class="button button-primary" value="{% trans 'Créer une annonce' %}" />
        </form>

    </div>


</div>
{% endblock %}